services:
  db:
    container_name: caardify-db
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    networks:
      - shared
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   container_name: link-pharmacy-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - shared

  pgadmin:
    container_name: caardify-pgadmin
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - shared

  # api:
  #   container_name: link-pharmacy-api
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - shared
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - path: apps/api/.env.docker

  # admin:
  #   container_name: link-pharmacy-admin
  #   build:
  #     context: .
  #     dockerfile: apps/admin/Dockerfile
  #   ports:
  #     - "3001:80"
  #   networks:
  #     - shared

  # depends_on:
  #   - api

  # prometheus:
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - shared

  # grafana:
  #   image: grafana/grafana-enterprise
  #   ports:
  #     - 3001:3000
  #   networks:
  #     - shared

  # minio:
  #   image: docker.io/bitnami/minio:2024
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - "./data/minio_data:/data"
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #     - MINIO_DEFAULT_BUCKETS=bucket
  #     - BITNAMI_DEBUG=true

  # elasticsearch:
  #   image: elasticsearch:7.9.2
  #   container_name: elasticsearch
  #   networks:
  #     - shared
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
  #     - "discovery.type=single-node"

  # # Kibana
  # kibana:
  #   image: kibana:7.9.2
  #   container_name: kibana
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - shared
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - "ELASTICSEARCH_URL=http://elasticsearch:9200"

networks:
  shared:
    driver: bridge
